### PR TITLE
[WIP] Add complex type

### PR DESCRIPTION
**Pull request by bonfus**
Add subroutines for comparing complex types.

### CODE REVIEW

**Comment by pdebuyl** [comment]
Hi bonfus, thank you for the Pull Request!

Is there any reason to have separated the real and imaginary parts? A short test with gfortran works fine with a single equality test, as in

```.f90
program ft1
  implicit none

  integer, parameter :: rk = selected_real_kind(10)

  complex(kind=rk) :: x1, x2

  x1 = (1, 2)
  x2 = x1

  write(*,*) x1 .eq. x2

end program ft1
```

**Comment by bonfus** [comment]
Hi pdebuyl,

you are correct, it's pointless. It's there because I'm also adding the `assert_close_c64` subroutines and I want to compare with `epsilon` and I kept the same syntax everywhere. 

By the way, I'm not even sure it's correct:

    program ma
    
    implicit none
    complex :: a (10)
    complex :: b(10)
    real :: eps=1
    
    eps = EPSILON(eps)
    
    a=(0,0)
    a=CMPLX(eps,eps)
    b=(0,0)
    
    print*,ABS(a-b) > eps
    
    print*,DBLE(a-b) > eps
    print*,AIMAG(a-b) > eps
    
    end program

gives:

    T T T T T T T T T T
    F F F F F F F F F F
    F F F F F F F F F F

I assumed that if real and complex parts are smaller than epsilon test should pass. Is that right?

**Comment by pdebuyl** [comment]
The distance between two complex numbers is a distance in the 2D plane, so the distance in your example is sqrt(2) times eps, and it fails the test of course.

It seems more consistent to me to use the euclidean distance to compare the number, in which case the separation between the components is superfluous. It makes more sense also from a programming point of view but code authors must be aware of the way it is done.

**Comment by bonfus** [comment]
> The distance between two complex numbers is a distance in the 2D plane, so the distance in your example is sqrt(2) times eps, and it fails the test of course.

Yes, this is clear. My doubt is that also something like this fails the test with `ABS`.


    program ma
    
    implicit none
    complex :: a (10)
    complex :: b(10)
    real :: eps=1
    
    eps = EPSILON(eps)
    
    a=CMPLX(0.8*eps,0.8*eps)
    b=(0,0)
    
    print*,ABS(a-b) > eps
    
    print*,DBLE(a-b) > eps
    print*,AIMAG(a-b) > eps
    
    end program

Anyway I'll get rid of the double comparison and complete the pull request.

**Comment by pdebuyl** [comment]
Strict equality checking should be reserved for peculiar situations.

The "go to" test that I use is `assert_close` that by default uses a tolerance of twice the epsilon. And that is already quite sensitive. (and settable when initializing the test object).

**Pull request merged**
