### PR TITLE
Improve support for multi kinds and add portable kinds and scripts license fixed

### PR DESCRIPTION
**Pull request by szaghi**
Improved kinds support with correct scripts license.

### CODE REVIEW

**Comment by pdebuyl** [comment]
Hi @szaghi,

Thanks for the update. I am almost over checking the PR.

A few questions:
1. doxygen recognizes the subroutine comment when it is placed /before/ the "subroutine" line.
   
   I have verified that this also suits FORD. Instead of
   
   ``` .f90
    subroutine init(this, tolerance32, tolerance64)
      !> Initialize the tester.
   ```
   
   you would have
   
   ``` .f90
    !> Initialize the tester.
    subroutine init(this, tolerance32, tolerance64)
   ```
2. The comment following the subroutine parameters need to be one per line only. Does it make any change for you?
3. The directive
   
   ```
   {!README-fortran_tester.md!}
   ```
   
   can be changed to
   
   ```
   {!../README.md!}
   ```
   
   and thus the file `doc/README-fortran_tester.md` removed. No problem with that?

I can make these changes after accepting the PR if you are ok.

Regards,

Pierre

**Comment by szaghi** [comment]
@pdebuyl 

I am very sorry, it is a long time I did not use doxygen. Sure, there is not problem with all your modifications, sorry for the _garbage_, I was too fast to write down it.

Cheers.

**Comment by pdebuyl** [comment]
@szaghi Thank you very much for your contribution!

**Comment by szaghi** [comment]
@pdebuyl Pierre, you are much more than welcome! I really like your tester, I'll use it extensively from now, that could be a bad news for you :smile:

**Pull request merged**
