### PR TITLE
remove fail flag

### PR DESCRIPTION
**Pull request by giacrossi**
I removed the fail flag from all the if in order to avoid unpredictable results.

### CODE REVIEW

**Comment by pdebuyl** [comment]
Thank you for the PR. I ping possibly interested developers to check whether they use `fail=.true.` in their codes. @bonfus @lettleli @szaghi

**Comment by giacrossi** [comment]
Hello: do you have any update on the PR?

**Comment by szaghi** [comment]
@pdebuyl For me Giacomo's PR is fine.

**Comment by pdebuyl** [comment]
Thank you @giacombum for the PR, @szaghi for the feedback.

**Comment by szaghi** [comment]
@pdebuyl you are welcome

**Pull request merged**
